// Telemetry sensor enable/disable configuration
// Uncomment to enable a sensor

//#define ENABLE_SENSOR_V_A3
//#define ENABLE_SENSOR_CELL_VOLTAGE_0
//#define ENABLE_SENSOR_CELL_VOLTAGE_1
//#define ENABLE_SENSOR_CELL_VOLTAGE_2
//#define ENABLE_SENSOR_CELL_VOLTAGE_3
//#define ENABLE_SENSOR_CELL_VOLTAGE_4
//#define ENABLE_SENSOR_CELL_VOLTAGE_5
#define ENABLE_SENSOR_LON
#define ENABLE_SENSOR_LAT
#define ENABLE_SENSOR_DATE
#define ENABLE_SENSOR_TIME
#define ENABLE_SENSOR_INAV_GNSS_PRECISION
#define ENABLE_SENSOR_SATS_IN_VIEW
#define ENABLE_SENSOR_GNSS_HEADING
#define ENABLE_SENSOR_GNSS_ALTITUDE
#define ENABLE_SENSOR_GNSS_SPEED
